### ISSUE TITLE
Increase idea limit on table

### ISSUE THREAD

**Issue by SamMurphyDev** [agiledigital-labs/confluence-plugin-idea-search#39]
The idea limit is capped at 20 and needs to be increased to incorporate all our ideas onto the table

https://github.com/agiledigital-labs/confluence-plugin-idea-search/blob/d54eafa0ad34e054163595008bf4c74f14e8a5d1/src/main/java/au/com/agiledigital/idea_search/macros/IndexTable.java#L170

**Comment by robinMcA** [comment]
Increased to 100.
We hope to have data coming through the API to the search before this limit is reached.
