### ISSUE TITLE
Page parenting process makes any index created page a child

### ISSUE THREAD

**Issue by SamMurphyDev** [agiledigital-labs/confluence-plugin-idea-search#45]
When creating a new page from the create button on an index page, it creates a page according to that blueprint type. E.g. technical article index page button creates a technical article page. Upon saving this page, the page is nested under the Fedex ideas page
![image](https://user-images.githubusercontent.com/3301215/107177540-30811700-6a26-11eb-885c-f8e706450846.png)

**Comment by shouvSarker** [comment]
This event listener is getting triggered on any blueprint create, not just Fedex idea blueprint create 

https://github.com/agiledigital-labs/confluence-plugin-idea-search/blob/main/src/main/java/au/com/agiledigital/idea_search/listener/FedexIdeaEventListener.java#L143

A possible fix is to check the blueprint id to verify if it is indeed our blueprint. We already save the blueprint id in our database, so it should be a quick fix.

Open to other approaches to solving this as well!

**Comment by shouvSarker** [comment]
Robin's current PR will fix this issue https://github.com/agiledigital-labs/confluence-plugin-idea-search/pull/48

**Comment by robinMcA** [comment]
This will still exist in the legacy/older version of the plugin. 

but should not be an issue in the new version as the feature to move pages unders the index page has been completly removed.

/close
